CREATE table IF NOT EXISTS CATEGORIES (
ID INTEGER PRIMARY KEY,
CAT_NAME TEXT UNIQUE,
CAT_DESCRIPTION TEXT,
CAT_PARENT_ID INTEGER
);

CREATE table IF NOT EXISTS PRODUCTS (
PROD_ID INTEGER PRIMARY KEY,
PROD_NAME TEXT,
PROD_DESCRIPTION TEXT,
PROD_MANUFACTURER TEXT,
PROD_TRADE_MARK TEXT,
PROD_CATEGORY_ID INTEGER NOT NULL,
CONSTRAINT unq UNIQUE (PROD_NAME, PROD_MANUFACTURER, PROD_TRADE_MARK)
);

CREATE table IF NOT EXISTS WH_ITEMS (
WH_ID INTEGER PRIMARY KEY,
WH_PRODUCT_ID INTEGER,
WH_QUANTITY BLOB,
WH_UNITS TEXT,
WH_PRICE BLOB
);

CREATE table IF NOT EXISTS SUPPLIES (
SUPPLIES_ID INTEGER PRIMARY KEY,
SUPPLIES_DATE INTEGER,
SUPPLIES_TYPE TEXT,
SUPPLIES_PRODUCT_ID INTEGER,
SUPPLIES_QUANTITY BLOB,
SUPPLIES_UNITS TEXT,
SUPPLIES_PRICE BLOB
);